### ISSUE TITLE
cog-prt-atomspace doesn't work in union of two atomspaces

### ISSUE THREAD

**Issue by sikefield3** [opencog/atomspace-rocks#20]
In the context of #15 , while testing the [Multiframe-Example](https://github.com/opencog/atomspace/blob/9aada20b12e120e7c80ece9a5432152852676bd7/examples/atomspace/multi-space.scm#L42-L45)
following happened:
When I tried to connect the union atomspace to a RocksDB and then try `cog-prt-atomspace`, I got a segfault.:
```
(cog-set-atomspace! c)
(define rsn (RocksStorageNode "rocks:///home/opcwdir/repodock/ForTestingStuff/foo.rdb"))
(cog-open rsn)
(store-atomspace)
(cog-prt-atomspace)
```
This happens also, if I use `cog-rocks-open`.
Printing the content with `cog-rocks-print` works fine.

Not sure, if this is a realistic use case.

**Comment by linas** [comment]
OK, I can reproduce this with the following
```
(use-modules (opencog) (opencog exec))
(use-modules (opencog persist))
(use-modules (opencog persist-rocks))

(define a (AtomSpace))
(define b (AtomSpace))
(define c (AtomSpace a b))

(cog-set-atomspace! a)
(Concept "I'm in A")
(cog-prt-atomspace)

(cog-set-atomspace! b)
(Concept "I'm in B")
(cog-prt-atomspace)

(cog-set-atomspace! c)
(define rsn (RocksStorageNode "rocks:///tmp/foo"))
(store-atomspace)
(cog-prt-atomspace)
```

**Comment by linas** [comment]
Fixed the crash, here:

https://github.com/opencog/atomspace/pull/3037

**Comment by linas** [comment]
Added unit test in 4499f340eee6305595529dfe6c1833e288171280

Closing; there's a fix, and a unit test for it. Thanks for the report!

**Comment by linas** [comment]
FWIW, I did NOT test beyond the above! There may still be bugs, weirdness, or unexpected behavior! The frame stuff is relatively new, and hasn't been hit hard by "real world" applications.
